### ISSUE TITLE
Possible unit conversion issue in example plot

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/Reporting-Engine#175] opened 2019-05-28 11:23 UTC
In the example project "Rifampicin-Midazolam", Fig. 2 and 3, the concentration of rifampicin (blue line) appears to be too low. The Cmax values are at around 4000 ng/ml and should be at around 12000. Correspondingly, the Ctrough values are below 200 ng/ml and should rather be at around 400. - The Midazolam curve appears to be correct.

![002_plotTimeProfile](https://user-images.githubusercontent.com/27352743/58474541-b7efff00-814b-11e9-9ceb-f54dbfefe815.png)
![003_plotTimeProfile](https://user-images.githubusercontent.com/27352743/58474545-b9b9c280-814b-11e9-914e-4954ee944b67.png)

**Comment by Yuri05** [comment] 2019-05-28 13:37
[02_Rifampicin-Midazolam-DDI.zip](https://github.com/Open-Systems-Pharmacology/Reporting-Engine/files/3227889/02_Rifampicin-Midazolam-DDI.zip)
Attached used project: 
 - **input/**: input for the qualification runner
 - **re_input/**: input for RE
 - **re_output/**: output of RE

The problem is with high probability wrong mol weight used in RE.
If PK-Sim values are multiplied with the ratio of Midazolam and Rifampicin mol weights, the result seems to be exactly what is output in RE

**Comment by Yuri05** [comment] 2019-05-29 15:53
should be fixed with the last PR
@UlrichSi please verify with the latest RE version (you can use the [reduced version from the comment above](https://github.com/Open-Systems-Pharmacology/Reporting-Engine/files/3227889/02_Rifampicin-Midazolam-DDI.zip))

**Closed as completed by Yuri05** 2019-05-29 15:53 UTC
Labels: prio: high
